# Generated by Django 5.0.1 on 2024-02-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('imageID', models.CharField(auto_created=True, max_length=7, null=True)),
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.CharField(max_length=15)),
                ('hotelName', models.CharField(max_length=50)),
                ('coordinateX', models.DecimalField(decimal_places=5, max_digits=8)),
                ('coordinateY', models.DecimalField(decimal_places=5, max_digits=8)),
                ('category', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=150)),
                ('openingTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('ratings', models.IntegerField(default=0)),
                ('isUserUploaded', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.TextField(max_length=20000)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.admin')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBeds',
            fields=[
                ('hotelID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotel.hotel')),
                ('noOfBeds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelBudget',
            fields=[
                ('budgetPackage', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelComments',
            fields=[
                ('commentID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('isApproved', models.CharField(max_length=3)),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwnerHotels',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
