# Generated by Django 5.0.1 on 2024-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='coordinateX',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='coordinateY',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
