# Generated by Django 4.2.6 on 2023-10-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=10)),
                ('AdminId', models.CharField(max_length=10)),
                ('IsApproved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('PlaceId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=10)),
                ('AdminId', models.CharField(max_length=10)),
                ('DateCreated', models.DateField()),
                ('ContactNumber', models.CharField(max_length=10)),
                ('PlaceName', models.CharField(max_length=250)),
                ('CoordinateX', models.DecimalField(decimal_places=1, max_digits=2)),
                ('CoordinateY', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Category', models.CharField(max_length=20)),
                ('Website', models.CharField(max_length=250)),
                ('OpeningHours', models.IntegerField()),
                ('UserReviews', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('IsUserUploaded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageUrl', models.CharField(max_length=250)),
                ('PlaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.place')),
            ],
        ),
    ]
