# Generated by Django 4.2.6 on 2024-02-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
    ]
