# Generated by Django 4.2.6 on 2024-02-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='adminId',
        ),
    ]
