# Generated by Django 4.2.6 on 2024-02-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0003_auto_20240203_2217"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="ratings",
            field=models.IntegerField(default=0),
        ),
    ]
