# Generated by Django 4.2.6 on 2024-02-10 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(db_column='userId', editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(db_column='userName', max_length=200)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, verbose_name='Email')),
                ('isBanned', models.CharField(db_column='isBanned', default='false', max_length=255)),
                ('country', models.CharField(db_column='country', max_length=15)),
                ('user_type', models.CharField(db_column='type', default='admin', max_length=15)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('isVerified', models.CharField(db_column='isVerified', default=0, max_length=8)),
                ('banExpirationDate', models.DateTimeField(blank=True, db_column='expirationDate', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('adminId', models.CharField(db_column='adminId', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('adminName', models.CharField(db_column='adminName', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=225, unique=True, verbose_name='Email')),
                ('country', models.CharField(db_column='country', max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.CharField(db_column='NotificationId', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField()),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.admin')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='adminId',
            field=models.ForeignKey(blank=True, db_column='adminId', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.admin'),
        ),
        migrations.CreateModel(
            name='GetNotification',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notificationId', models.ForeignKey(db_column='NotificationId', on_delete=django.db.models.deletion.CASCADE, to='account.notification')),
            ],
        ),
    ]
