# Generated by Django 4.2.7 on 2023-12-15 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('adminId', models.UUIDField(db_column='adminId', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adminName', models.CharField(db_column='adminName', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=225, unique=True, verbose_name='Email')),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.UUIDField(db_column='NotificationId', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField()),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.admin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.UUIDField(db_column='userId', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isBanned', models.BooleanField(db_column='isBanned', default=False)),
                ('country', models.CharField(db_column='country', max_length=15)),
                ('type', models.CharField(db_column='type', max_length=15)),
                ('adminId', models.ForeignKey(blank=True, db_column='AdminId', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.admin')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='GetNotification',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notificationId', models.ForeignKey(db_column='NotificationId', on_delete=django.db.models.deletion.CASCADE, to='account.notification')),
            ],
        ),
    ]
