# Generated by Django 4.2.6 on 2024-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='adminId',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationId',
            field=models.AutoField(db_column='NotificationId', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(db_column='isVerified', default=False),
        ),
    ]
