# Generated by Django 4.2.6 on 2024-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banExpirationDate",
            field=models.DateTimeField(
                blank=True, db_column="expirationDate", null=True
            ),
        ),
    ]
