# Generated by Django 4.2.6 on 2023-12-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userName",
            field=models.CharField(db_column="userName", default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="adminId",
            field=models.ForeignKey(
                blank=True,
                db_column="adminId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.admin",
            ),
        ),
    ]
