# Generated by Django 4.2.6 on 2023-10-22 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_tc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "adminId",
                    models.UUIDField(
                        db_column="AdminId",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adminName", models.CharField(db_column="AdminName", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        db_column="Email",
                        max_length=225,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                ("country", models.CharField(db_column="Country", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                db_column="Country", default="default", max_length=15
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="isBanned",
            field=models.BooleanField(db_column="IsBanned", default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(db_column="Type", default="default", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="userId",
            field=models.UUIDField(
                db_column="UserId",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_column="Email", max_length=255, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_column="Name", max_length=200),
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
        migrations.AddField(
            model_name="user",
            name="adminId",
            field=models.ForeignKey(
                blank=True,
                db_column="AdminId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.admin",
            ),
        ),
    ]
