# Generated by Django 4.2.6 on 2024-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_banexpirationdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(db_column="type", default="admin", max_length=15),
        ),
    ]
