# Generated by Django 4.2.6 on 2023-12-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_created_at_remove_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
    ]
