# Generated by Django 4.2.6 on 2023-11-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_admin_remove_user_id_user_country_user_isbanned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(
                db_column="UserId",
                editable=False,
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
