# Generated by Django 4.2.6 on 2024-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.AutoField(
                db_column="userId", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
