# Generated by Django 4.2.6 on 2023-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(
                db_column="UserId",
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
