# Generated by Django 4.2.6 on 2024-02-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_isverified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="adminId",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notificationId",
            field=models.AutoField(
                db_column="NotificationId",
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
