# Generated by Django 4.2.6 on 2023-12-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_admin_groups_admin_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="admin",
            table="admin",
        ),
    ]
