# Generated by Django 4.2.6 on 2023-12-15 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_admin_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="admin",
            name="adminId",
            field=models.UUIDField(
                db_column="adminId",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="adminName",
            field=models.CharField(db_column="adminName", max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="country",
            field=models.CharField(db_column="country", max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(db_column="email", max_length=254, unique=True),
        ),
    ]
