# Generated by Django 4.2.6 on 2023-12-15 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_admin_is_active_remove_admin_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="adminId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="adminName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
