# Generated by Django 4.2.6 on 2023-12-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_admin_adminid_alter_admin_adminname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="last_login",
        ),
    ]
