# Generated by Django 4.2.6 on 2023-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_admin_is_superuser_remove_admin_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isBanned",
            field=models.CharField(db_column="isBanned", max_length=100),
        ),
    ]
