# Generated by Django 4.2.6 on 2023-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_remove_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pwd",
            field=models.CharField(db_column="password", default="", max_length=100),
            preserve_default=False,
        ),
    ]
