# Generated by Django 4.2.6 on 2023-12-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_pwd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="password",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="admin",
            name="pwd",
            field=models.CharField(db_column="password", default="", max_length=100),
            preserve_default=False,
        ),
    ]
