# Generated by Django 4.2.6 on 2023-12-15 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_remove_admin_pwd_remove_user_pwd_admin_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="user",
            name="userName",
        ),
        migrations.AlterField(
            model_name="admin",
            name="adminId",
            field=models.UUIDField(
                db_column="adminId",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="adminName",
            field=models.CharField(db_column="adminName", max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="country",
            field=models.CharField(db_column="country", max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(
                db_column="email", max_length=225, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="adminId",
            field=models.ForeignKey(
                blank=True,
                db_column="AdminId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.admin",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="isBanned",
            field=models.CharField(db_column="isBanned", max_length=255),
        ),
    ]
