# Generated by Django 4.2.6 on 2023-12-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_remove_admin_groups_remove_admin_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="adminId",
            field=models.CharField(
                db_column="adminId",
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notificationId",
            field=models.CharField(
                db_column="NotificationId",
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(
                db_column="userId",
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
