# Generated by Django 4.2.6 on 2023-12-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_admin_adminid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="adminId",
        ),
        migrations.DeleteModel(
            name="GetNotification",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
