# Generated by Django 4.2.6 on 2023-12-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_notification_adminid_delete_getnotification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="adminId",
            field=models.ForeignKey(
                blank=True,
                db_column="adminId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.admin",
            ),
        ),
    ]
