# Generated by Django 4.2.6 on 2023-12-17 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_user_adminid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notificationId",
                    models.CharField(
                        db_column="NotificationId",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("dateTime", models.DateTimeField()),
                (
                    "adminId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.admin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GetNotification",
            fields=[
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notificationId",
                    models.ForeignKey(
                        db_column="NotificationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.notification",
                    ),
                ),
            ],
        ),
    ]
