# Generated by Django 4.2.6 on 2023-12-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_notification_getnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
