# Generated by Django 4.2.6 on 2023-12-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_admin_last_login_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=50),
        ),
    ]
