# Generated by Django 4.2.6 on 2023-12-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_user_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userName",
            field=models.CharField(db_column="userName", default="", max_length=200),
            preserve_default=False,
        ),
    ]
