# Generated by Django 4.2.6 on 2023-12-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isBanned",
            field=models.CharField(
                db_column="isBanned", default="false", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(db_column="type", default="local", max_length=15),
        ),
    ]
