# Generated by Django 4.2.6 on 2023-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_user_isverified_onetimepassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(db_column="type", default="traveler", max_length=15),
        ),
    ]
