# Generated by Django 4.2.6 on 2023-12-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_alter_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="type",
            new_name="user_type",
        ),
    ]
