# Generated by Django 4.2.6 on 2023-12-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_rename_type_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_provider",
        ),
    ]
