# Generated by Django 4.2.6 on 2023-12-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_remove_user_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isVerified",
            field=models.BooleanField(default="False"),
        ),
    ]
