# Generated by Django 4.2.6 on 2023-12-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_alter_user_isverified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
    ]
