# Generated by Django 4.2.6 on 2023-12-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0029_alter_user_isverified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="isVerified",
        ),
    ]
