# Generated by Django 4.2.7 on 2023-12-15 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=50)),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('scheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
    ]
