# Generated by Django 4.2.6 on 2024-02-03 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=50)),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('destination', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('att', models.CharField(max_length=500, null=True)),
                ('hotels', models.CharField(max_length=500, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
