# Generated by Django 4.2.6 on 2024-02-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0031_user_auth_provider_user_isverified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("scheduleId", models.AutoField(primary_key=True, serialize=False)),
                ("partner", models.CharField(max_length=50)),
                ("fromDate", models.DateTimeField()),
                ("toDate", models.DateTimeField()),
                ("destination", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserSchedule",
            fields=[
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripType",
            fields=[
                (
                    "type",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "scheduleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                    ),
                ),
            ],
        ),
    ]
