# Generated by Django 5.0.1 on 2024-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='x',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='y',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
