# Generated by Django 4.2.6 on 2023-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
