# Generated by Django 4.2.6 on 2024-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_destination_alter_schedule_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='att',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
