# Generated by Django 4.2.6 on 2024-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
