# Generated by Django 4.2.6 on 2024-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_x_schedule_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='x',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='y',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
