# Generated by Django 4.2.6 on 2024-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0002_alter_advertisement_adid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="adId",
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
